### ISSUE TITLE
Player Reports

### ISSUE THREAD

**Issue by qbcore-framework** [qbcore-framework/qb-inventory#1]
Player reported: 

- When cops search players they can only see the first two rows of their inventory
- The rob command does not work
- Sometimes does not give items unless fast slots are empty

**Comment by meistroburger** [comment]
Rob command is working, you first need to cuff the player (with handcuffs) then escort and than you can rob them

**Comment by DaShizz** [comment]
how do i disable the cuff ? i need to be able rob without the person being cuffed

**Comment by ImJustKiddinDude** [comment]
how do i stop it that every player can see reports?
