### ISSUE TITLE
Why was the size of the inv reduced through html and css ?

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-inventory#105]
Why was this thing done?
Why was the inv size reduced?
Why imitate other invs "linden_inventory"?
I hope the size of the bag will return to the screen as it was in the beginning

This size was perfect for the vision
Yes, it is now an annoying choice
https://camo.githubusercontent.com/abba3b2acc735f9945fcd11009c9c6ebef09287ce45e7109859c04ef8836a8c9/68747470733a2f2f696d6775722e636f6d2f6351577251344c2e706e67

https://ibb.co/895rd99

I wish the bag could be back in size

**Comment by evanillaa** [comment]
I wish I could restore the default size inv
we are here qbcore not other inv

**Comment by evanillaa** [comment]
It's uncomfortable to look
It's annoying because it's so small
Why is she small?

**Comment by darknight2590** [comment]
You're right, it's too small
