### ISSUE TITLE
The stash is not working on the latest version

### ISSUE THREAD

**Issue by RuisSoftware** [qbcore-framework/qb-inventory#123]
I can put items in the stash without errors. It does save it in the database.
But when i reopen the stash, the items are all gone.

This version does work: https://github.com/qbcore-framework/qb-inventory/tree/036cf1939f14f51652b6f973ff0681425cc9033a

In the latest version, the stash is the only thing that does not work.

**Comment by GhzGarage** [comment]
Could not reproduce. Make sure your sql is right!
