### ISSUE TITLE
Inventory Drop Marker

### ISSUE THREAD

**Issue by scrubh** [qbcore-framework/qb-inventory#132]
Found the problem on inventory drop markers. If you drop item on the floor and your friend is close and drop item too it go broke

part 2. if you drop the item in like east and dont pick it up and then tpm to north and drop something and pick it up, the drop market wont dissapear

https://user-images.githubusercontent.com/91434926/137657271-55643cf1-744a-4144-9f44-c4e867b90771.MOV

**Comment by Mekz1222** [comment]
#142 That will fix your issue
