### ISSUE TITLE
You should make some improvement on the css Cuz there is issues for those who have small screen

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-inventory#148]
You should make some improvement on the css Cuz there is issues for those who have small screen ... before the last css update he was good

**Comment by GhzGarage** [comment]
Have a screenshot?

**Comment by OxGhali** [comment]
![aa](https://user-images.githubusercontent.com/71113131/141519726-3c04d19d-90ef-4df4-a139-4e70ff8e98d6.png)

**Comment by GhzGarage** [comment]
Ok just use the old css for now then

**Comment by OxGhali** [comment]
okay thank you anyway
