### ISSUE TITLE
crafting not working 

### ISSUE THREAD

**Issue by davelawless1989** [qbcore-framework/qb-inventory#192]
Hi i am still new to codes but i can't get it to work 
i am getting is 
SCRIPT ERROR @qb-inventory/client/main.lua165; attempt to a nil value (field 'name')
> ItemsToItemInfo (@qb-inventory/client/main.lua:165)
>GetThresholdItem (@qb-inventory/client/main.lua:221)
>fn (@qb-inventory/client/main.lua:860)

Many thanks Dave

**Comment by CptNoHand** [comment]
same for me

**Comment by Duguayster** [comment]
Same error here as well.
