### ISSUE TITLE
[BUG] The amount of weight exceeds the allowable limit

### ISSUE THREAD

**Issue by MercedessBenz** [qbcore-framework/qb-inventory#208]
**Video implementation of the bug**

https://streamable.com/t4aaqf

**Comment by whoops1e** [comment]
+1

**Comment by restray** [comment]
Hey ! Can you update and giva me a text so we know how to replicate it :)

**Comment by restray** [comment]
Should be patch on v1.0.0 (+ No news, closing it for inactivity)
