### ISSUE TITLE
max ammo function doesn't work

### ISSUE THREAD

**Issue by kawo420** [qbcore-framework/qb-inventory#217]
if i enter a limit i can still carry more ammunition

**Comment by kawo420** [comment]
still can't get the function in the config to work, but found another solution with an edited weapon.meta file

**Comment by ALFAMAS** [comment]
> still can't get the function in the config to work, but found another solution with an edited weapon.meta file

Can you Share That

**Comment by ItsANoBrainer** [comment]
What does this even mean?
