### ISSUE TITLE
[Suggestion] (QoL) Item-Stack Manipulation Keybinds

### ISSUE THREAD

**Issue by kunaiknife452** [qbcore-framework/qb-inventory#221]
Keybinds to move/grab an entire stack of items would be a great QoL change. Similar to Minecraft in functionality.

Example Functionality:
Shift + Left Click -- grabs the entire stack of items, regardless of the current number set to move with standard left-click 
(functions the same as left-click does when item number is set to 0)

Shift + Right Click -- sends the entire stack into the other inventory (stash,store,etc)

**Comment by restray** [comment]
There is actually very close functionnality in the inventory, can you pull the updates and let me know ! :)

**Comment by restray** [comment]
Re-open it when you can make a better explanation of your suggestion !
