### ISSUE TITLE
[question] Adding stress relief items?

### ISSUE THREAD

**Issue by gerardojro** [qbcore-framework/qb-inventory#222]
Trying to add a cigarette to the inventory to accomplish the same effect as smoking a joint. I duplicated the joint events on client/server and changed the interactions. I also added the item in shared but got an error every time.

Anybody have a Wiki on how to create such items? 

Thanks!

**Comment by ItsANoBrainer** [comment]
Github issues is for problems, not generic support on how to work things. Use Discord for support.
