### ISSUE TITLE
[suggestion] Inventory Settings

### ISSUE THREAD

**Issue by JajarGaming** [qbcore-framework/qb-inventory#223]
## Inventory Settings

I was wondering the inventory could maybe have some kind of settings tab, maybe a blur would be toggleable. This would work through the SQL databse by taking the user inventory settings and putting them on when the player loads it. I will provide some pictures below with some previews(Taken from nopixel)

![image](https://user-images.githubusercontent.com/71441748/151677098-2375df8d-97f6-4f2d-b2f5-f9904e661469.png)
![image](https://user-images.githubusercontent.com/71441748/151677101-6a8ae80b-eb79-4225-8413-92dc6ab6379f.png)

**Comment by restray** [comment]
First of all: don't save user preference in SQL! With JavaScript you can easily access a Storage that's on the player's disk (faster loading for him, no useless informations on db, ...)

The settings you told about are, now, easy to integrate! If you know how to code, feel free to open a PR to add this :)

But this ticket will be closed in 1 month (no news, and no comments at all!)

**Comment by restray** [comment]
I'm back! This won't be done because those can be done by servers owners as their needs!
