### ISSUE TITLE
Script Error: Execution of Native 9f47b058362c84b5

### ISSUE THREAD

**Issue by Brady-F** [qbcore-framework/qb-inventory#224]
When attempting to open the inventory inside smoke on the water, this error occurs. I have been unable to get this occur anywhere else. 

![image](https://user-images.githubusercontent.com/55960318/152689617-1c27c034-bc4b-436c-8be6-65fd4f428830.png)

![image](https://user-images.githubusercontent.com/55960318/152689633-ed9405af-e44a-4934-a60b-6f2c1629a61b.png)

**Comment by restray** [comment]
Hey!
Some news ? Did you tried updating ?

**Comment by restray** [comment]
Inactive, closing it! Re-open if needed
