### ISSUE TITLE
Cash as item

### ISSUE THREAD

**Issue by Najtin19** [qbcore-framework/qb-inventory#225]
Hello, i really want to add cash as item, but i don't know how to do that to work with legacyfuel, qb-banking and anything that needs cash. I know that cash as item can be really buggy. I saw this thing github.com/PuFGGs/cash-item-for-qb-core
but it really doesn't work well with qb-banking i can't deposit my money and on LegacyFuel i can't refuel because "I dont have enough cash" and there is probably a lot of other things that uses cash and don't work with that "cash-item-for-qb-core". Thank you very much for any help. (all on qb-framework of course)

**Comment by restray** [comment]
Hello, please check the #266 to get more infos!
