### ISSUE TITLE
Calling Player.Functions.RemoveItem(item, amount, slot) can cause errors if called more then once.

### ISSUE THREAD

**Issue by w0rthi3** [qbcore-framework/qb-inventory#226]
Calling above function to remove an item doesn't actually clear the item from the PlayerData.items table and will allow you to call it again and attempt to remove it again but instead just errors out.

**Comment by ItsL3w1s** [comment]
To also extend on this when a play moves/gives an item in their inventory the PlayerData.items table doesn't update on the server and can cause issues when looking through player inv with a for loop

**Comment by restray** [comment]
Hey! Can you give us some updates about this? Which file are you talking about, your initial issue?
