### ISSUE TITLE
AttachmentCrafting issue

### ISSUE THREAD

**Issue by SharkyFP** [qbcore-framework/qb-inventory#229]
When at AttachmentCraftingLocation the drawtext doesn't work. I keep getting an error:
![image](https://user-images.githubusercontent.com/70804183/153776405-465f5a95-d15a-42b4-b884-dd7c84d7a4d9.png)

**Comment by MasteerMR** [comment]
Hello, good, I have the same problem that the person above is showing and I don't know how to fix it and someone knows to answer one of the 2 that we need help

**Comment by SharkyFP** [comment]
> Hello, good, I have the same problem that the person above is showing and I don't know how to fix it and someone knows to answer one of the 2 that we need help

DM if you need help
©Sharky#4793
So I managed to fix it so it works.
[atachment.txt](https://github.com/qbcore-framework/qb-inventory/files/8069748/atachment.txt)

**Comment by restray** [comment]
Should be patch in the last commits do not hesitate to re-open the ticket if it doesn't work for you
