### ISSUE TITLE
[bug fix] qb-inventory: nil reference when multiple near drops avaliable

### ISSUE THREAD

**Issue by deandum** [qbcore-framework/qb-inventory#237]
Link to PR: https://github.com/qbcore-framework/qb-inventory/pull/228

There is an issue with the CurrentDrop assignment when there is more than one near drop visible. CurrentDrop is always set to nil if there are multiple elements in the DropsNear table and the player is not close enough to the first element.

To reproduce it, drop two items at close range, but not in the same drop. Now check to see if you can access both of them successfully.

The new version of the script will loop through all the Drops, then find all the DropsNear elements, and then set the CurrentDrop to the ID that is closest to the current player location. Tested it locally while creating drops from dead NPCs and it seems to work better.

**Comment by restray** [comment]
Hey! You don't need to open an issue if you already done a PR previously!

I'll look into your PR asap!

**Comment by restray** [comment]
Re-open the ticket if it's needed, as the pull request were refused!
