### ISSUE TITLE
Error on js when i try to use crafting mode

### ISSUE THREAD

**Issue by iglesiiaskeviin** [qbcore-framework/qb-inventory#244]
![image](https://user-images.githubusercontent.com/55926245/157148433-e90201f6-2bd5-4d1b-b442-de651d2f26db.png)
When I try to drag the object from the crafting area to my inventory, it does nothing, it does not remove the items that it is supposed to remove and it also throws an error in the js

**Comment by restray** [comment]
Hey, your issue is kinda old but: to begin, your qb-inventory is not on the latest version or you modified it (https://github.com/qbcore-framework/qb-inventory/blob/daec4fe4c49085770110ed908f318f6142d2e2a8/html/js/app.js#L798).
Try to update or go on the QBCore Discord.

**Comment by restray** [comment]
Should be patch with last commit
