### ISSUE TITLE
Image Attachments Weapon not working great

### ISSUE THREAD

**Issue by milotiro95** [qbcore-framework/qb-inventory#246]
Hello everyone.

I troubleshoot this night on some image for the attachments on a weapon doesn't show.
I check into shared/items.lua for them and everything is good name / img and the img also exist into qb-inventory/html/images
I check into the config of qb-weapons and it's look like good also.
But i cannot have the image working properly anybody has this issue ?

Sorry for my bad english. 
![Sans titre](https://user-images.githubusercontent.com/86166328/157480515-1696a705-9e01-4e80-80da-f22b6006afa3.png)

**Comment by restray** [comment]
Hey!

Your image should be in the `html/attachment_images/` folder ! And this absolutely need to be a ".png" file!

Keep me in touch or close this issue if resolved!

**Comment by milotiro95** [comment]
Hey @restray thank you for help.
Unfortunately I just try to put into attachments and seems to have the same issue ! It's a .png file 100x100 image per exemple scope not working but in item they have a good image (in my inventory i see it) but when I'm putting into a attachment the image just not load like the image. As you see I have successfully update image on suppressor, flash and grip (only flash will show at the start).  /: I just don't understand why i check into qb-weapons config and into shared/item and all looks good -.-

**Comment by restray** [comment]
./images/{weapon_type:smg,pistol...}_attachmentName.png

Try something like this!

**Comment by milotiro95** [comment]
![1](https://user-images.githubusercontent.com/86166328/160039113-8fcc5c57-1891-417c-b18d-d0bc6274c14b.png)
![2](https://user-images.githubusercontent.com/86166328/160039116-6e686eea-15e8-4f21-a0ec-ce4d70d0fa52.png)

**Comment by restray** [comment]
Could you show me in the images folder all the weapon attachment .png files you have ?

**Comment by milotiro95** [comment]
Actually all is in html/images if I put them in attachment the image not working but yes i can show you if needed

**Comment by milotiro95** [comment]
Ham I see carbinerifle_scope in html/images is working now with a replace for rifle_scope. Do you have an idea why ?

**Comment by milotiro95** [comment]
Okey @restray I just understand how it work I will fix all my errors then ! Thank you a lot for the help I was desperate to get it work ! I close this bug report ! Love you! :)
