### ISSUE TITLE
[JS] Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by KingRyuShin** [qbcore-framework/qb-inventory#247]
Trying to buy an item from the shop give me this error : 

![image](https://user-images.githubusercontent.com/42899923/158745720-4b507b31-70fe-4c7c-856a-75e47057a2eb.png)
![image](https://user-images.githubusercontent.com/42899923/158745824-d4882bdb-efad-4690-a3bf-338492c192e6.png)

 here i still have the normal shop with all item displayed, it only happen when moving from the other inventory to my inventory

**Comment by KingRyuShin** [comment]
the problem I found is that the name of the supermarket doesn't appear anymore but if i go to hardware store, everything is working perfectly

![image](https://user-images.githubusercontent.com/42899923/158751946-ea590052-21f0-4978-883a-a2fdb2491520.png)

**Comment by KingRyuShin** [comment]
Fixed, closing this

**Comment by ahmoge** [comment]
sorry how did you fix this
