### ISSUE TITLE
[BUG] cant open WeaponAttachments

### ISSUE THREAD

**Issue by xenfovn** [qbcore-framework/qb-inventory#254]
video : https://streamable.com/lalf12
F8 :
![image](https://user-images.githubusercontent.com/55439243/160590335-9cea2e93-658a-4ac1-8042-9fc205f6ec24.png)

**Comment by xenfovn** [comment]
@restray

**Comment by ShomyTKD** [comment]
Have you tried pressing on the weapon and then on Attachments instead of dragging it? Pretty sure that works for me

**Comment by restray** [comment]
There is actually 2 different versions for the inventory, one the master branch and the other on the dev branch.

On the dev branch the only way to open attachment menu was to drop the weapon on the attachment button!
This one had a bug which is normally resolved but the new inventory version is not ready for production yet (we need testers and others)

**Comment by ShomyTKD** [comment]
Ah, gotcha. I am willing to help, just say it! :)

**Comment by restray** [comment]
It should be resolve, please test it on the dev branch! (Remember to pull updates please!)
