### ISSUE TITLE
KeyBind not getting changed !! 

### ISSUE THREAD

**Issue by erpofficial** [qbcore-framework/qb-inventory#259]
`RegisterKeyMapping('inventory', 'Open Inventory', 'keyboard', 'tab')`

changed this to 

`RegisterKeyMapping('inventory', 'Open Inventory', 'keyboard', 'k')`

Still key bind not get changed to K from tab

**Comment by restray** [comment]
To begin: Hello

Then, did you check you in-games settings. The `RegisterKeyMapping` doesn't update existing keys (it only set a key alias to a command).

And if it still doesn't work open a new ticket with screenshots, and more informations about the things you have done, the version you are on, etc...
