### ISSUE TITLE
no items switch one box to another

### ISSUE THREAD

**Issue by buntyverma69** [qbcore-framework/qb-inventory#264]
![image](https://user-images.githubusercontent.com/72088153/161774859-dc7d52e9-2bf6-4bd0-898e-02eb80ee1951.png)

**Comment by BerkieBb** [comment]
Dev or main branch?

**Comment by buntyverma69** [comment]
> Dev or main branch?

dev

**Comment by BerkieBb** [comment]
@restray

**Comment by restray** [comment]
Do you have set an amount in the middle box?

**Comment by buntyverma69** [comment]
> Do you have set an amount in the middle box?

nope

**Comment by restray** [comment]
So set an amount... If there is nothing in it, it can't work yep

**Comment by buntyverma69** [comment]
> So set an amount... If there is nothing in it, it can't work yep

https://streamable.com/ltz79w see these

**Comment by buntyverma69** [comment]
> Very weird... I'll dive into this issue tonight!

alright

**Comment by restray** [comment]
Check this, normally this should patch your bug! :D

**Comment by buntyverma69** [comment]
> Check this, normally this should patch your bug! :D



> Check this, normally this should patch your bug! :D

yeah great

**Comment by buntyverma69** [comment]
> Check this, normally this should patch your bug! :D



> Check this, normally this should patch your bug! :D

yeah great

**Comment by IdrisDose** [comment]
Fixed in dev branch
