### ISSUE TITLE
#6 Locked slot

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-inventory#275]
I increased my slots from 41 to 75 and the 6 Locked slot moved way down towards the bottom of the inventory. Anyone know how to fix this and bring it back to the top while still maintaining 75 slots?

Also, I'm confused on the max inventory slots in the config file. There is a max slot config in the QBCore config file and also one in the qb-inventory config file. The one in the QBCore config file doesn't seem to do anything. Does anyone have any insight? Thank You!!
```
QBConfig.Player.MaxInvSlots = 75 -- Max inventory slots for a player
MaxInventorySlots = 75
```

![image](https://user-images.githubusercontent.com/43043270/164745181-ce7e4520-9454-4a1e-be20-86cc2987400c.png)

**Comment by izMystic** [comment]
the 6th hotbar slot goes off of the 41st slot in the inventory, its supposed to be on the bottom

**Comment by erikmeyer08** [comment]
Thanks!
