### ISSUE TITLE
[SUGGESTION] Better trunk implementation 

### ISSUE THREAD

**Issue by TonybynMp4** [qbcore-framework/qb-inventory#278]
My ideas is to add a ['trunk'] in qb-core/shared/vehicles.lua to have different trunk sizes depending on the vehicle and not on the class,
Also adding a trunk to trailers because i believe they currently can't have one (i might be weong tho).

That would allow a new way of balancing vehicles on the item transportation field and it would allow to fix some vehicles having trunks when they shouldn't for example (like semi-trucks being in the same category as the pounder even tho they'd need a trailer, or the Ultralight that shouldn't be able to hold items where a velum might be used to transport stuff)

**Comment by MadManDanCat** [comment]
I love this idea

**Comment by GhzGarage** [comment]
Closing since PR's are made. Thanks

**Comment by arkjoker** [comment]
how use 2024 qbcore
