### ISSUE TITLE
[BUG][security] DUPLICATE ANY ITEM IN YOUR INV

### ISSUE THREAD

**Issue by PT-Mohamed-Hussein** [qbcore-framework/qb-inventory#283]
**Describe the bug**
just duplicate any item through any job i will show u video on how to reproduce it and u can try it with any job 

**To Reproduce**
https://youtu.be/4LlWMjzQuBk

**Expected behavior**
it is expected to give me x number of stones not of uranium

**Screenshots**
https://youtu.be/4LlWMjzQuBk

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 qb-target 
 qb-mining
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
yes to `ww-` to avoid the register key mapping issue
**Additional context**
i think its some thing with slots bec the glitch is only happens when u have 0 item from the expected item u will recieve for example 
if i have 0 stone the problem showed above will happen while if i have 1 stone it wont happen

**Comment by 19adorest** [comment]
> **Describe the bug** just duplicate any item through any job i will show u video on how to reproduce it and u can try it with any job
> 
> **To Reproduce** Steps to reproduce the behavior: https://youtu.be/4LlWMjzQuBk
> 
> **Expected behavior** it is expected to give me x number of stones not of uranium
> 
> **Screenshots** https://youtu.be/4LlWMjzQuBk
> 
> **Questions (please complete the following information):**
> 
>     * When you last updated: [e.g. last week]
> 
>     * Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
>       qb-target
>       qb-mining
> 
>     * Have you renamed `qb-` to something custom? [e.g. yes/no]
>       yes to `ww-` to avoid the register key mapping issue
>       **Additional context**
>       i think its some thing with slots bec the glitch is only happens when u have 0 item from the expected item u will recieve for example
>       if i have 0 stone the problem showed above will happen while if i have 1 stone it wont happen

my man.. the inventory on your video is from [Inventory](https://github.com/loljoshie/lj-inventory), so you need to ask the author how to fix that.

**Comment by PT-Mohamed-Hussein** [comment]
> > **Describe the bug** just duplicate any item through any job i will show u video on how to reproduce it and u can try it with any job
> > **To Reproduce** Steps to reproduce the behavior: https://youtu.be/4LlWMjzQuBk
> > **Expected behavior** it is expected to give me x number of stones not of uranium
> > **Screenshots** https://youtu.be/4LlWMjzQuBk
> > **Questions (please complete the following information):**
> > ```
> > * When you last updated: [e.g. last week]
> > 
> > * Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
> >   qb-target
> >   qb-mining
> > 
> > * Have you renamed `qb-` to something custom? [e.g. yes/no]
> >   yes to `ww-` to avoid the register key mapping issue
> >   **Additional context**
> >   i think its some thing with slots bec the glitch is only happens when u have 0 item from the expected item u will recieve for example
> >   if i have 0 stone the problem showed above will happen while if i have 1 stone it wont happen
> > ```
> 
> my man.. the inventory on your video is from [Inventory](https://github.com/loljoshie/lj-inventory), so you need to ask the author how to fix that.

Actually same issue goes to qb one but i couldmt make the vid for it alone

**Comment by 19adorest** [comment]
> Actually same issue goes to qb one but i couldmt make the vid for it alone

Have you try this one? #263

**Comment by aalbonn** [comment]
You basically add progressbar to inventory open function and remove items before progressbar

### RegisterNetEvent('inventory:client:OpenInventory',` function(PlayerAmmo, inventory, other)
    QBCore.Functions.Progressbar("player123", "You are accessing", 500, false, false, {
		disableMovement = true,
		disableCarMovement = true,
		disableMouse = false,
		disableCombat = true,
		}, {
		}, {}, {}, function()
            if not IsEntityDead(PlayerPedId()) then
                ToggleHotbar(false)
                SetNuiFocus(true, true)
                if other then
                    currentOtherInventory = other.name
                end
                SendNUIMessage({
                    action = "open",
                    inventory = inventory,
                    slots = MaxInventorySlots,
                    other = other,
                    maxweight = QBCore.Config.Player.MaxWeight,
                    Ammo = PlayerAmmo,
                    maxammo = Config.MaximumAmmoValues,
                })
                inInventory = true
            end
	end, function()
        print("canceled")
	end)
end)

**Comment by PT-Mohamed-Hussein** [comment]
guys have u see the video ? before trying give me fixes ?

**Comment by TransitNode** [comment]
You can only replicate this bug with jobs that drop items on the ground? Not all jobs drop items on the ground. qb-mining doesn't seem to be officially apart of this framework could you link us the source of the qb-mining you are using?
