### ISSUE TITLE
[BUG] Ammo don't load

### ISSUE THREAD

**Issue by Im-Kayun** [qbcore-framework/qb-inventory#291]
**Describe the bug**
For example: if I have a carbine rifle and reload the weapon with rifle_ammo and then switch to another weapon, the ammunition will be consumed but the weapon will not be reloaded.

**To Reproduce**
1. Put Carbine Rifle in 1st slot and equip it
2. Put Rifle ammo in 2nd slot and equip it
3. Put other weapon in 3rd slot
4. Before the ammunition is equipped, quickly select to the slot of another weapon
5. Finally the rifle ammo item will be consumed, but the gun will not be reloaded

**Expected behavior**
When you choose another weapon the reload is cancelled

**Screenshots**
I don't have

**Questions (please complete the following information):**
 - When you last updated: 3/4 weeks
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
Not necessary

**Comment by martink1337** [comment]
Same problem with me :)

**Comment by ChatDisabled** [comment]
At the time intended and known. Simple had to move one line back. Currently following the code shouldn't happen anymore.
