### ISSUE TITLE
[BUG] Remove attachments weapon

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-inventory#299]
I can't delete weapon attachments.
video: https://cdn.discordapp.com/attachments/992405259651649647/992419534285848686/2022-07-01_20-14-41.mp4

**Comment by peppinoita** [comment]
Same problem for me. Inventory does not recognise attachments mounted on weapons

**Comment by martink1337** [comment]
The problem is same with me also, when you add attachment on some weapon, you can't remove it. The script doesn't recognize that you added an attachment on the weapon!

**Comment by XLightDev** [comment]
I closed the code line 18, it can see the attachments normally.

![image](https://user-images.githubusercontent.com/108535266/179693248-b3d67a60-d594-4a60-82b3-0dbcf0468c7d.png)

**Comment by Scullyy** [comment]
Fixed in #305
