### ISSUE TITLE
[BUG] [Critical] Item duplication bug

### ISSUE THREAD

**Issue by santahashi** [qbcore-framework/qb-inventory#302]
How to reproduce: 

1) Have 2 items. Item A for duping number, item B is the item you want to dupe.
2) Throw the item B to the ground. Item A is in your inventory.
3) Open inventory, swap the item you want to dupe (B) with the Item A
4) Keep swapping from item B to item A (follow this sequence, don't swap A to B)
5) Close the inventory when item A is in the inventory (not on the ground)
6) Open the inventory, Voila!

Video: https://streamable.com/e5x7qv

**Comment by XLightDev** [comment]
I also found such a bug.

**Comment by XLightDev** [comment]
You must not modify the label, it will not be able to do bugs.

![image](https://user-images.githubusercontent.com/108535266/179700375-9186059f-00f5-4910-983b-077b4483cd58.png)

**Comment by XLightDev** [comment]
If you want to edit the label, you must also edit the .js section as shown below.

It won't be able to do bugs :)

![image](https://user-images.githubusercontent.com/108535266/179701769-2e79abcd-2504-4958-aa71-a522dc4edf04.png)

![image](https://user-images.githubusercontent.com/108535266/179701868-9d46e0ef-4d5c-4f3b-9e61-1055913b1643.png)

![image](https://user-images.githubusercontent.com/108535266/179701950-0c675eed-122f-47e0-a000-9af3a7e4d2ea.png)

**Comment by santahashi** [comment]
Thank you

> If you want to edit the label, you must also edit the .js section as shown below.
> 
> It won't be able to do bugs :)
> 
> ![image](https://user-images.githubusercontent.com/108535266/179701769-2e79abcd-2504-4958-aa71-a522dc4edf04.png)
> 
> ![image](https://user-images.githubusercontent.com/108535266/179701868-9d46e0ef-4d5c-4f3b-9e61-1055913b1643.png)
> 
> ![image](https://user-images.githubusercontent.com/108535266/179701950-0c675eed-122f-47e0-a000-9af3a7e4d2ea.png)

Thank you :)

**Comment by XLightDev** [comment]
I'm having trouble merging items.

better not fix
