### ISSUE TITLE
[BUG] Fix Bug Remove attachments weapon

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-inventory#304]
I removed line 18 of code, it can see attachments normally.

![image](https://user-images.githubusercontent.com/108535266/179694195-a79be105-6288-49ad-bfa4-ba28f7595281.png)

![image](https://user-images.githubusercontent.com/108535266/179693248-b3d67a60-d594-4a60-82b3-0dbcf0468c7d.png)

**Comment by Sylvernl88** [comment]
In #306 code still in it
