### ISSUE TITLE
Stash for  jobs [SUGGESTION]

### ISSUE THREAD

**Issue by stanibee** [qbcore-framework/qb-inventory#316]
hi i have question , is there posible to create  stash for jobs  ? is there command for that or  code ?

**Comment by Z3rio** [comment]
Hello mate! This is already possible. You can open a stash in the inventory by using the following events:
```lua
TriggerServerEvent("inventory:server:OpenInventory", "stash", "STASHID")
TriggerEvent("inventory:client:SetCurrentStash", "STASHID")
TriggerServerEvent("InteractSound_SV:PlayOnSource", "StashOpen", 0.4)
```
(The interact sound event isnt needed although gives the player a better experience).
Just make sure that the "STASHID" is something unique and the same for both events.

**Comment by ChatDisabled** [comment]
Just to add, you can take a look at examples from other resources e.g. https://github.com/qbcore-framework/qb-policejob/blob/main/client/job.lua#L851-L867
