### ISSUE TITLE
Inventory wont open no errors  [BUG]

### ISSUE THREAD

**Issue by Andey2021** [qbcore-framework/qb-inventory#320]
The inventory will sometimes open but 9 times out of 10 it bugs and wont open for anyone no matter what we do to get it open we cant use items on the hotbar when this happens and cant access the full inventory system.

I have no errors on the back end of the server and no errors when this happens.

the only way to get the inventory working again is by manually restarting the resource

could you tell me a fix for this or even let me know what could be causing this

**Comment by sinphoenix** [comment]
Have you tried to replace the script itself?
