### ISSUE TITLE
[BUG] HasItem Error

### ISSUE THREAD

**Issue by MrAg135** [qbcore-framework/qb-inventory#328]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Buy lockpick
2. Use lockpick
3. Get this error : QBCore:HasItem is deprecated, please use QBCore.Functions.HasItem, it can be used on both server- and client-side and uses the same arguments.

**Questions (please complete the following information):**
 - When you last updated: Last Update
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by BerkieBb** [comment]
It's not an error

**Comment by BerkieBb** [comment]
The callback still works, it just tells you to use another function instead of that
