### ISSUE TITLE
[BUG] - RemoveItem

### ISSUE THREAD

**Issue by mirrox1337** [qbcore-framework/qb-inventory#337]
**Describe the bug**
If you consume an item with hotkey twice the item will be consumed twice and give no effect, even if progressbar is running. I don't remember this being a problem before inventory changes

**To Reproduce**
1. Put a consumable on a hotkey
2. Fat-fingerer the hotkey twice
4. Item gets removed twice

**Expected behavior**
Remove the item once

**Screenshots**
https://streamable.com/taurw0

**Questions (please complete the following information):**
 **- When you last updated: [e.g. last week]**

>  Today (2022-08-26)

 **- Are you using custom resource? which ones? [e.g. zdiscord, qb-target]**

>  lj-inventory

 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 
> No

**Additional context**

**Comment by BerkieBb** [comment]
This would fit more in qb-smallresources, as the issue lies there, not in qb-inventory, qb-smallresources removes the item before it triggers the event to eat, meaing nothing is stopping the usage and removal of the item, only the client side implementation
