### ISSUE TITLE
[BUG] script:qb-core] SCRIPT ERROR: @qb-core/server/functions.lua:262: No such export CreateUsableItem in resource qb-inventory

### ISSUE THREAD

**Issue by XxDeezixX** [qbcore-framework/qb-inventory#339]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**
owned stores stopped working so i updated qb-inventory now im getting  script:qb-core] SCRIPT ERROR: @qb-core/server/functions.lua:262: No such export CreateUsableItem in resource qb-inventory

**Comment by Molicheu** [comment]
function QBCore.Functions.CreateUseableItem(item, data)
    QBCore.UsableItems[item] = data
end

**Comment by Molicheu** [comment]
The export is not through qb-inventory anymore it's through qb-core

**Comment by XxDeezixX** [comment]
> The export is not through qb-inventory anymore it's through qb-core

How do i add it to the qbcore now? thanks

**Comment by XxDeezixX** [comment]
> The export is not through qb-inventory anymore it's through qb-core
function QBCore.Functions.CreateUseableItem(item, data)
QBCore.UsableItems[item] = data
end ?

**Comment by D4isDAVID** [comment]
> > The export is not through qb-inventory anymore it's through qb-core
> 
> How do i add it to the qbcore now? thanks.......new error attempt to compare number with nil

Consider updating qb-core.
