### ISSUE TITLE
[BUG] Weapon attachment not showing

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-inventory#345]
**Describe the bug**
Weapon attachment not showing in inventory

**To Reproduce**
try to equip a weapon attachment and click on that gun then go to attachment tab there will nothing 

**Expected behavior**
Should show weapon attachment those are attached to that particular gun

**Screenshots**
[[If applicable, add screenshots to help explain your problem.](https://streamable.com/0mkpfd)
](https://streamable.com/0mkpfd)
**Questions (please complete the following information):**
 - When you last updated: [just installed fresh tx 5 min ago]
 - Are you using custom resource? which ones? [fresh tx install no other resource motive to check the attachment]
 - Have you renamed `qb-` to something custom? [no]

**Comment by nzkfc** [comment]
Im running through a fresh update also and noticed this issue is back again, was tyring to find the fix that was PR'ed a few months ago to see what the issue was.
