### ISSUE TITLE
script error [BUG]

### ISSUE THREAD

**Issue by Andey2021** [qbcore-framework/qb-inventory#346]
on server start up and player load in we get this error 

[ script:qb-inventory] SCRIPT ERROR: @qb-inventory/server/main.lua:1068: attempt to call a nil value (field 'AddPlayerMethod')
[ script:qb-inventory] > handler (@qb-inventory/server/main.lua:1068)
[ script:qb-inventory] > [global chunk] (@qb-core/server/player.lua:538)
[ script:qb-inventory] > ref (@qb-core/server/player.lua:24)
[ script:qb-inventory] > <unknown> (@oxmysql/dist/build.js:21958)
[ script:qb-inventory] > runMicrotasks (<anonymous>:0)
[ script:qb-inventory] > processTicksAndRejections (node:internal/process/task_queues:96)
[ script:qb-inventory] > async rawExecute (@oxmysql/dist/build.js:21911)

anyone know a fix for this

**Comment by D4isDAVID** [comment]
Your qb-core is probably outdated, try updating it.

**Comment by Andey2021** [comment]
ill try that now but i think im running at the current version

**Comment by Andey2021** [comment]
it is updated to the latest version of qb core but still getting the same error

**Comment by D4isDAVID** [comment]
I can't replicate this issue with latest qb-inventory and qb-core. Please update them.

**Comment by Aigle12** [comment]
same probb
