### ISSUE TITLE
@qb-inventory/server/main.lua:1423: attempt to call a nil value (field 'Notify')

### ISSUE THREAD

**Issue by Nik0lovD** [qbcore-framework/qb-inventory#349]
**Brand new instalation of qb-framework**
 I did not edit anything.... and there r this error... 
 Can someone help?

**Comment by D4isDAVID** [comment]
Update your [qb-core](https://github.com/qbcore-framework/qb-core).

**Comment by MiroslavDina** [comment]
i was made too qb-core update and issue persist, after reboot server
