### ISSUE TITLE
[BUG] No Such export LoadInventory in resource qb-inventory

### ISSUE THREAD

**Issue by Fear6682** [qbcore-framework/qb-inventory#356]
### Summary

I am stuck on a black screen after creating character (multicharacter) and theres an error in console

### Reproduction

I started to reinstall all the QB-Core scripts because everything was having issues and most of it was outdated and I used to have AJ-Inventory but qb-inventory is needed for the new QB scripts so idk what the issue is but I've installed both scripts with the latest versions. I am stuck on a black screen after creating character (multicharacter) and theres an error in console:
![QB-Core Error](https://user-images.githubusercontent.com/113636227/191364512-b9d336d3-f19a-4851-9329-899a362200c6.PNG)

### Expected behavior

The scripts to update and for the inventory and other scripts to work

### Actual behavior

Nothing is linking including the resources I need to load into the server (inventory, multicharacter, spawn)

### Additional context

I don't have all the dependencies because qb-logs github page has been closed and I can't find a new version anywhere else

### Last Updated

today

### Custom Resources

A lot (300+)

### Resource Rename

No

**Comment by coderwashere** [comment]
i have the same issue after install new inventory

**Comment by hilolo** [comment]
me 2

**Comment by UnboundGodz** [comment]
> i have the same issue after install new inventory
> me 2

Make sure you update both qb-core and qb-inventory, restart of server is required.

**Comment by BlackBullGames** [comment]
i updated qb-core, qb-inventory and qb-multicharacter and have the same issue still

**Comment by AltyS-CZ** [comment]
I have this as of 1/6/2023 what is the fix?

**Comment by nergoto1** [comment]
Same problem.

**Comment by Christian819** [comment]
Has anyone fixed this because I have qb-logs, but still didnt make a difference!

**Comment by jattgurry** [comment]
Any one got solution o this yet?

**Comment by ppolshark120502** [comment]
![image](https://github.com/qbcore-framework/qb-inventory/assets/72841575/f23ec42c-cec3-43d9-8df2-e437b997e33c)
Any one got solution on this yet? ive been strugging for weeks trying to fix this

**Comment by MrTaylor2910** [comment]
Open the code qb-core/server/player.lua and got to line 162 and send me a picture i believe it's also line 494 you have to change as well but I've managed to fix this error and get back onto my server

**Comment by MrTaylor2910** [comment]
Open the code qb-core/server/player.lua and got to line 162 and send me a picture i believe it's also line 494 you have to change as well but I've managed to fix this error and get back onto my server.![IMG_20230828_133200.jpg](https://github.com/qbcore-framework/qb-inventory/assets/88213541/3e715850-2c2b-4806-bf4c-e4a59b44f50d)

![IMG_20230828_133216.jpg](https://github.com/qbcore-framework/qb-inventory/assets/88213541/af464096-bed3-4fa1-9cc5-8547a9564170)

**Comment by Lazpal** [comment]
**Same problem.**
![image](https://github.com/qbcore-framework/qb-inventory/assets/136169818/51366634-d8c5-4f06-8aec-ec629d35cee0)

**Comment by QrixA** [comment]
how to fix it?

**Comment by QrixA** [comment]
> Open the code qb-core/server/player.lua and got to line 162 and send me a picture i believe it's also line 494 you have to change as well but I've managed to fix this error and get back onto my server.![IMG_20230828_133200.jpg](https://private-user-images.githubusercontent.com/88213541/263702601-3e715850-2c2b-4806-bf4c-e4a59b44f50d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODkzODMsIm5iZiI6MTcwNTM4OTA4MywicGF0aCI6Ii84ODIxMzU0MS8yNjM3MDI2MDEtM2U3MTU4NTAtMmMyYi00ODA2LWJmNGMtZTRhNTliNDRmNTBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA3MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZDRlNDk1NTdhY2U5NDQ2ZjYxZTc3YzIyYjU5NWM2MWU5YmU4ZjJlYzczNjFiOTAzZGM3NzliYjlmYTJmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9FE60BMv_BHLFevoXO-B-rHsxoUVG8bXyPpvg8sQJHQ)
> 
> ![IMG_20230828_133216.jpg](https://private-user-images.githubusercontent.com/88213541/263702629-af464096-bed3-4fa1-9cc5-8547a9564170.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODkzODMsIm5iZiI6MTcwNTM4OTA4MywicGF0aCI6Ii84ODIxMzU0MS8yNjM3MDI2MjktYWY0NjQwOTYtYmVkMy00ZmExLTljYzUtODU0N2E5NTY0MTcwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA3MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNzQ3MDYyY2I5NzZlMzRkNjhlYTkwNTZjNTc1OTk0OGIxNDMxMzViM2NiYTNiOGQ4MWRiYjk1NmFjZmMyMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v12FBm1h0LjXeJV9aqW4La8OgXDFHapt6onoy06FFMU)

![image](https://github.com/qbcore-framework/qb-inventory/assets/97265178/e70de739-7174-412d-aa9a-1665b424c681)
can u solve it?

**Comment by lama-development** [comment]
For all the people having this problem, download [qb-inventory](https://github.com/qbcore-framework/qb-inventory) by the big green button named "**CODE**", AND NOT through the release page. That's what fixed it for me. I think they should have a look at that.
