### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Liamw1204** [qbcore-framework/qb-inventory#357]
### Summary

Cant transfer in traphouse inventory

### Reproduction

Go to trap house and open traphouse inventory

### Expected behavior

Be able to drag and drop items

### Actual behavior

Nothing its like the inventory freezes

### Last Updated

Today

### Custom Resources

No

### Resource Rename

No

**Comment by ihr-it-projekt** [comment]
see PR: https://github.com/qbcore-framework/qb-inventory/pull/406
