### ISSUE TITLE
Can't change key for inventory

### ISSUE THREAD

**Issue by JaxDanger** [qbcore-framework/qb-inventory#36]
I am trying to change the key for the qb-inventory as I personally do not like how it's currently TAB to open and close.
I have been trying for the past 10 minutes trying to replace the keybind with something other than tab.
Each time I've done this, I've either restarted the server, or the resource to update it and nothing works.

In case anyone is wondering where I am changing the keybind, I am changing it in qb-inventory/client/client.lua and if you scroll down some, you'll see this:
RegisterKeyMapping('inventory', 'Open Inventory', 'keyboard', 'TAB')

Now, I've replaced the TAB part with a test key like "j", but after a restart of the resource, it is still binded to TAB

**Comment by BerkieBb** [comment]
The inventory works with keymapping, meaning that you can change the keybind yourself, after you've changed the keybind, the change only applies to new players that join after the change as it can't overwrite your own keybinds, only set it if it's not there, so if you change the keybind, all existing players have to change it too
