### ISSUE TITLE
[BUG] No cursor in inventory

### ISSUE THREAD

**Issue by Jorn08** [qbcore-framework/qb-inventory#369]
### Summary

Sometimes when opening an inventory the NUI focus is lost, having no cursor while the inventory is visible.

### Reproduction

Using the txAdminRecipe 2.2.4

Enter the default qb-traphouse. Use the 'Take Over ($5000)'. Then press View Inventory.

### Expected behavior

Expected the inventory to have NUI focus.

### Actual behavior

The inventory does not have NUI focus.

### Additional context

Pressing 'View Inventory' triggers `qb-traphouse:client:target:ViewInventory`, which in turn triggers `inventory:server:OpenInventory`. This server event triggers the following two client events
```lua
TriggerClientEvent("qb-inventory:client:closeinv", id)
TriggerClientEvent("inventory:client:OpenInventory", src, {}, Player.PlayerData.items, secondInv)
```

To these client events I have added logs to track the flow. 

![image](https://user-images.githubusercontent.com/33311549/197786372-b9d38232-1a39-4970-9ba5-1c580658b45f.png)

As you can see the events as well as the js code they are calling are handled in the order they are executed, `qb-inventory:client:closeinv` first then `inventory:client:OpenInventory`. Except the `Inventory.Close` javascript functions calls the callback `https://qb-inventory/CloseInventory` which executes after the inventory had already opened. This causes a race condition.

This bug was introduced two months ago by [this commit](https://github.com/qbcore-framework/qb-inventory//commit/f2929a7461897d92a67601fc23a4fa0a499ec028).

### Last Updated

Yesterday

### Custom Resources

No

### Resource Rename

No

**Comment by TheMaf021** [comment]
This is what worked for me:
- Remove TriggerClientEvent("qb-inventory:client:closeinv") from the qb-inventory/server.lua (line 1417)
- Add TriggerEvent("qb-inventory:client:closeinv") as a new line (19) in smallresources/handsup.lua (right under the export)
    - Intent is that if someone uses the /hu command, close inventory. 
- Add TriggerEvent("qb-inventory:client:closeinv") as a new line (291) in dpemotes/client/emotes.lua
    - Intent is that no matter what /e command you use, it will close inventory

Traphouse is now working for me.

**Comment by tom-osborne** [comment]
This was fixed for qb-traphouse in https://github.com/qbcore-framework/qb-traphouse/pull/45
