### ISSUE TITLE
Add more improvements

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-inventory#37]
We know that every weapon has a default age (decreases with use)
Why not apply this to all the items in the project
For example when using
lockpick
advlockpick
diving_gear
radio
handcuffs
all items

durability system
https://github.com/vanillla1/qb-core1
https://github.com/vanillla1/qb-inventory
https://github.com/vanillla1/qb-durability

**Comment by vanillla1** [comment]
durability system
https://github.com/vanillla1/qb-core1
https://github.com/vanillla1/qb-inventory
https://github.com/vanillla1/qb-durability
@JericoFX @GhzGarage

**Comment by justinttw** [comment]
@vanillla1 There seems to be an issue where if an admin gives an item to the player and that the item is not unique and the item already exist in the player's inventory, the player add item function (in the server player.lua) just changes the amount of the existing item. Is there a way to change that?
