### ISSUE TITLE
[BUG]Some items put in trunks disappear & Items in trunk when pulled out duplicate 

### ISSUE THREAD

**Issue by SlimChances** [qbcore-framework/qb-inventory#374]
### Summary

When putting items into trunks and stashes they disappear and if they dont you can pull them out but the item stays in the stash/trunk

### Reproduction

1.Putting a lockpick in a trunk the item stays.
2.Putting a lighter in the trunk the item disappears 
3.Pulling the lockpick out of the trunk (quantity 1) the lockpick gets put into players inventory but is still in the stash/trunk.

### Expected behavior

The items should be staying in the trunk and when the player pulls the items out of their trunk they trunk item should be removed.

### Actual behavior

1.When putting a lockpick in a trunk the item stays.
2.When putting a lighter in the trunk the item disappears 
3.When pulling the lockpick out of the trunk (quantity 1) the lockpick gets put into players inventory but is still in the stash/trunk.

### Additional context

Newest version fresh download of the updated resource.

### Last Updated

today

### Custom Resources

no

### Resource Rename

no

**Comment by Total-Role-Play** [comment]
I am having this same issue, I am going to go diagnose it because its causing a mass dupe of items on my server and this is not good for the economy.

**Comment by strongprincess** [comment]
im habing this issue is there any idea or fixes

**Comment by Mauro1197** [comment]
I have the same problem, can you help me??
