### ISSUE TITLE
[BUG] In-inventory crafting not working?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-inventory#377]
### Summary

Combining items that have been setup as inventory crafting doesn't work

### Reproduction

1. Spawn lockpick and screwdriverset
2. Drag one onto the other
3. Nothing happens

### Expected behavior

It should combine into an advancedlockpick as per the qb-core\shared\items.lua combine code

### Actual behavior

Makes a noise, does nothing.

### Additional context

https://youtu.be/Z3Myt8sNYUk

### Last Updated

Today

### Custom Resources

100% pure QB reciepie as of today

### Resource Rename

Nope

**Comment by tom-osborne** [comment]
@nzkfc According to `items.lua` dropping a `screwdriverset` onto a `lockpick` should create an `advancedlockpick`
However, dropping a `lockpick` onto a `screwdriverset` will do nothing.

Can you confirm you were doing it the right way around? i.e. dropping a `screwdriverset` onto a `lockpick`

**Comment by nzkfc** [comment]
I've tried it both ways in multiple slots and players report also who use
it daily, but I will retest tonight on fresh as well

**Comment by nzkfc** [comment]
Yep still happening on fresh pull as of today. I also tested gatecrack and electronickit and they don't combine either to get the trojan_usb item.

**Comment by mikepauer** [comment]
It broke with #376 as that's the only recent change I've pulled into my inventory, and it's broken on my install too.

**Comment by tom-osborne** [comment]
Thanks, will check it out

**Comment by nzkfc** [comment]
> It broke with #376 as that's the only recent change I've pulled into my inventory, and it's broken on my install too.

@tom-osborne I have reverted the change from #376 on a fresh pull and re-tested, can confirm that the issue still exists so I don't believe 376 caused it.

**Comment by mikepauer** [comment]
> > It broke with #376 as that's the only recent change I've pulled into my inventory, and it's broken on my install too.
> 
> @tom-osborne I have reverted the change from #376 on a fresh pull and re-tested, can confirm that the issue still exists so I don't believe 376 caused it.

Interesting, as I reverted ours to just (fromData.amount == $toAmount) and right away combine started working again, and swapping item slots started working again (with 376 combine wasn't working, and dragging non-unique items from one slot to another was no longer swapping them).

**Comment by tom-osborne** [comment]
Reverting fixes combining for me. Debugging now.

**Comment by tom-osborne** [comment]
@nzkfc @mikepauer Please test #378

**Comment by nzkfc** [comment]
You sure you didn't have the other fix that someone put into PR to try fix
the items going poof?

**Comment by tom-osborne** [comment]
What?

**Comment by nzkfc** [comment]
Oh it didn't quote the other guy, I was checking with him if he was using
your PR in conjunction with #348 which was open for a bit when this issue
was logged (but also broke stacking)

**Comment by nzkfc** [comment]
> @nzkfc @mikepauer Please test #378

Pulled another fresh build just in case.

Testing:
- Dragged items onto each other, both the wrong way and correct way, can confirm correct way now works, makes the "Combine" and "Switch" buttons appear in middle of inventory and you can now craft (combine) the items.

- Tested crafting table just to double check, all ok

- Re-tested the original fix for items going missing, all working as expected. Did an extra test of filling a boot with pistols and trying to move more in or dragging more in, it correctly detects it's full andd stops you from doing so.

Looks like this is good to go, again thanks for the solid fixes here @tom-osborne
