### ISSUE TITLE
[SUGGESTION] Blacklist items

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-inventory#379]
### The problem

Enable a blacklist for inventory items from being robbed.

### Ideal solution

something like

Config.ItemRobBlacklist= {
   'weapon_bat',
   'weapon_combatpistol',
    

### Alternative solutions

Having to use 3rd party gun rack scripts or some sort of silly rule admins have to babysit for certain weapons not to be robbed.

**Comment by xdrahmahx** [comment]
upvote this.
