### ISSUE TITLE
Stash doesn't save in database

### ISSUE THREAD

**Issue by thatsimpressive** [qbcore-framework/qb-inventory#38]
When dragging items to any stash and exiting for it to save, if you hop back in the stash the item that you dragged is no longer in the stash and just vanishes.

When checking the SQL info all there is in items is `[]` (https://i.imgur.com/aJ5YcJH.png)
Setup: https://i.imgur.com/RIQUsDH.png

No errors on client or server.

**Comment by GhzGarage** [comment]
Server side error?

**Comment by thatsimpressive** [comment]
No errors anywhere. It just disappears as soon as you close the stash.

However, trunk & glovebox work, but the items don't get stored in the database either.

**Comment by GhzGarage** [comment]
Just did a fresh txAdmin install to check and it worked for me

**Comment by thatsimpressive** [comment]
I have no clue what is happening. I just did a fresh install with the txAdmin recipe and I'm still getting the same issue.

However, I am now able to see the items in the database for about a minute or so before it just disappears (the item still does not appear in the stash - and it took me leaving the apartment and coming back to get that far)

**Comment by p4zinee** [comment]
i got it too, open glovebox or trunk or stash this will disappear don't know to to got it

**Comment by JericoFX** [comment]
i just tested and work, https://streamable.com/ko4bfv

**Comment by thatsimpressive** [comment]
Here's my issue in full - https://youtu.be/nG2W0fWfM_M 

I tried to make it go by as quick as I could, but it's still 8 minutes long (you can skip ahead near the end if you want to see my issue).

**Comment by JericoFX** [comment]
did you drop the tables?, i have to do that to ensure my rows are created correctly

**Comment by CrypticOG** [comment]
I too was having this same issue.

**Comment by fishiidev** [comment]
This is happening to me

**Comment by RexShack** [comment]
same issue here as well / stash items not saving

**Comment by thatsimpressive** [comment]
[This commit](https://github.com/qbcore-framework/qb-inventory/commit/036cf1939f14f51652b6f973ff0681425cc9033a) has fixed my issue 😄
