### ISSUE TITLE
[BUG] OpenInventory loses focus

### ISSUE THREAD

**Issue by JonasDev17** [qbcore-framework/qb-inventory#383]
### Summary

OpenInventory loses focus

### Reproduction

Triggering the following event:
TriggerServerEvent("inventory:server:OpenInventory", "otherplayer", target)

where target is a players source.

### Expected behavior

The inventory of the other players opens where you can move items.

### Actual behavior

The inventory opens but loses focus.

The Issue is here:
https://github.com/qbcore-framework/qb-inventory/blob/6d6b14e59a7894f7653c1e97362488fc9cab3026/server/main.lua#L1420

closeInv does SetNuiFocus(false, false) but after SetNuiFocus(true, true) of inventory:server:OpenInventory.

One solution which is not very nice but works is add a delay between the events.

### Last Updated

about 3 weeks ago

### Custom Resources

none

### Resource Rename

no

**Comment by XxDeezixX** [comment]
i love the inventory for the qbcore you did. my best one. on the next update you do could you add the inventory weight so we could see how much room we have left in our pockets and car trunks thank you boss keep up the best work
