### ISSUE TITLE
Prevent Inventory Spam Opening

### ISSUE THREAD

**Issue by IdrisDose** [qbcore-framework/qb-inventory#41]
Hey, I noticed an issue when playing with the inventory if you press and hold the tab it will spam the inventory opening animation.

To fix this should be simple:
in `client/main.lua:114`:
```
RegisterCommand('inventory', function()
    if not isCrafting then
        if not inInventory then
              -- PlayerData function.....
        end
    end
end)
```

Thanks, was going to make a PR but perhaps it might be a simple fix just to put in issues.

**Comment by BerkieBb** [comment]
Small fixes can be put in a pull request too, even if it is 1 character that changed, nothing is a problem

**Comment by CaptnSloth** [comment]
@ IdrisDose I test and dont work as tab is both a open and close function I just edited the app.js 

$(document).on('keydown', function() {
    switch(event.keyCode) {
        case 27: // ESC
            Inventory.Close();
            break;
        case 8: // Backspace
            Inventory.Close();
            break;
    }
});

**Comment by josh-tf** [comment]
I've submitted a PR here which solves the above issues and keeps the same key to open/close:

https://github.com/qbcore-framework/qb-inventory/pull/48

**Comment by IdrisDose** [comment]
> I've submitted a PR here which solves the above issues and keeps the same key to open/close:
> 
> #48

Thanks heaps!

I forgot to submit my PR but I did pretty much the same thing.
