### ISSUE TITLE
[BUG] SCRIPT ERROR: @qb-inventory/server/main.lua:185: attempt to call a nil value (field 'SetPlayerData')

### ISSUE THREAD

**Issue by JeoyGaming** [qbcore-framework/qb-inventory#412]
### Summary

I can't give items to people, I can't buy from the shop

### Reproduction

I can't give items to people, I can't buy from the shop

### Expected behavior

no

### Actual behavior

no

### Additional context

no

### Last Updated

oggi

### Custom Resources

no

### Resource Rename

no

**Comment by Brekeriello** [comment]
hello did you solve? i need some help
