### ISSUE TITLE
[BUG] How to remove open inventory animation?

### ISSUE THREAD

**Issue by owlel** [qbcore-framework/qb-inventory#413]
### Summary

Open Inventory animation messes with weapon draw

### Reproduction

The animation is slow for some reason in my server when it comes to opening the inventory and drawing a weapon afterwards, when I draw my weapon my arms are still in the animation to open my inventory. Im looking through configs and seeing where I can possibly remove this animation to help? If anyone knows where it may be.

![image](https://user-images.githubusercontent.com/122576774/214753242-b5b61a2a-90a4-4f77-8c1f-6b740a763fa1.png)

### Expected behavior

For us to draw our weapons faster and normally. 

### Actual behavior

Hands are glitched and stuck in the open inventory animation for 2 seconds, while drawing and shooting my gun.

### Last Updated

This week

### Custom Resources

qb-core

### Resource Rename

No

**Comment by vipexv** [comment]
![image](https://user-images.githubusercontent.com/101529155/216195888-785875e9-30b1-4a13-89d5-fbb0be61e4a6.png)

**Comment by vipexv** [comment]
Client/Main.lua, it should be that, not sure tho, you can go ahead and simply remove the function or just remove line of code that executes that function, i would suggest the second option since this function i'm guessing is used a lot.

**Comment by vipexv** [comment]
Yeah i found it, don't delete the function, simply remove this line of code.
![image](https://user-images.githubusercontent.com/101529155/216196181-ce026554-9f05-4d1b-b141-4ba1b7008f7b.png)

**Comment by Mexdrimbe** [comment]
I don't know if I'm answering late. But if you still need help with that, follow the instructions below

here is the code that makes you do an animation when you open the inventory: 

local function openAnim()
    LoadAnimDict('pickup_object')
    TaskPlayAnim(PlayerPedId(),'pickup_object', 'putdown_low', 5.0, 1.5, 1.0, 48, 0.0, 0, 0, 0)
end

so what you want to do is you simply just change 5.0, 1.5, 1.0, 48, 0.0, 0, 0, 0 to 0.0, 0.0, 0.0, 00, 0.0, 0, 0, 0

Hope this helped even though I'm replying late.

**Comment by Mexdrimbe** [comment]
> Don't delete the function, simply remove this line of code. ![image](https://user-images.githubusercontent.com/101529155/216196253-a8a89f70-209a-4cab-a71d-b8cebe5f166d.png)

this is wrong
