### ISSUE TITLE
Swapping items from main inventory and stash

### ISSUE THREAD

**Issue by CriMsOnN** [qbcore-framework/qb-inventory#43]
Hello i noticed a bug where if you try to swap 2 items that are the same but not stackable like weapons you lose one of the two.
Example.
One on the main inventory slot 5 and the other one on stash inventory slot 5 if you try to swap them one will disappear.
That happens only if they are on the same slot. If they are on different slot both get into stash instead of swapping.

Video:
https://streamable.com/du2pv3

**Comment by ihyajb** [comment]
@GhzGarage I tested the PR and it worked. Dont have to merge now just a btw

**Comment by GhzGarage** [comment]
I made a simpler edit @CriMsOnN 

![image](https://user-images.githubusercontent.com/57848836/129431392-dd5c35a4-a8cb-4034-8b06-0ab9f6e54dfd.png)

**Comment by GhzGarage** [comment]
Try that and see if it works for you. It did for me

**Comment by GhzGarage** [comment]
I also commented out the removeitem function at line 440
