### ISSUE TITLE
[BUG] Slow loading stashes?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-inventory#430]
### Summary

Stashes are loading as NONE

### Reproduction

Use stash, says NONE if ya too quick (only happens sometimes)

### Expected behavior

Check stash is open before showing it I guess, if NONE then close and notify player that stash didn't open or something.

### Actual behavior

Stash opens as none, still shows inventory but then when you drop anything in, it puts it into a drops which player cannot access.

### Additional context

https://outplayed.tv/media/P7WOyK

### Last Updated

Been an issue for ages, just happens now and then.

### Custom Resources

N/a

### Resource Rename

No

**Comment by eygi** [comment]
have you fixed this?

**Comment by nzkfc** [comment]
I believe so, not from an actual fix, I think I just uplifted the inventory
and core at some point and it fixed itself.
