### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by ReNsTeR501** [qbcore-framework/qb-inventory#467]
### The problem

Greetings guys, quick enhancement question for you, i'd like to see a setting in config to hard set marked bills to a single value, this should allow them to stack without any issue. ty

### Ideal solution

right now, marked bill dont stack due to the values of each being different, if it could just be hard set to a single value via the config, people can decide which they prefer :)

### Alternative solutions

no alternative soluteion

**Comment by citRaTTV** [comment]
You can accomplish this by setting `unique = false` in your items.lua file in qb-core. IE change:
```lua
    markedbills                  = { name = 'markedbills', label = 'Marked Money', weight = 1000, type = 'item', image = 'markedbills.png', unique = true, useable = false, shouldClose = true, combinable = nil, description = 'Money?' },
```
to
```lua
    markedbills                  = { name = 'markedbills', label = 'Marked Money', weight = 1000, type = 'item', image = 'markedbills.png', unique = false, useable = false, shouldClose = true, combinable = nil, description = 'Money?' },
```

**Comment by ReNsTeR501** [comment]
niceeeeee, ty for letting me know.

**Comment by AngryMaximus** [comment]
> You can accomplish this by setting `unique = false` in your items.lua file in qb-core. IE change:
> 
> ```lua
>     markedbills                  = { name = 'markedbills', label = 'Marked Money', weight = 1000, type = 'item', image = 'markedbills.png', unique = true, useable = false, shouldClose = true, combinable = nil, description = 'Money?' },
> ```
> 
> to
> 
> ```lua
>     markedbills                  = { name = 'markedbills', label = 'Marked Money', weight = 1000, type = 'item', image = 'markedbills.png', unique = false, useable = false, shouldClose = true, combinable = nil, description = 'Money?' },
> ```

This won't work considering marked bills are nested with meta data, the price / value of the marked bills will only ever be the last marked bill you got.

**Comment by citRaTTV** [comment]
> > You can accomplish this by setting `unique = false` in your items.lua file in qb-core. IE change:
> > ```lua
> >     markedbills                  = { name = 'markedbills', label = 'Marked Money', weight = 1000, type = 'item', image = 'markedbills.png', unique = true, useable = false, shouldClose = true, combinable = nil, description = 'Money?' },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```lua
> >     markedbills                  = { name = 'markedbills', label = 'Marked Money', weight = 1000, type = 'item', image = 'markedbills.png', unique = false, useable = false, shouldClose = true, combinable = nil, description = 'Money?' },
> > ```
> 
> This won't work considering marked bills are nested with meta data, the price / value of the marked bills will only ever be the last marked bill you got.

That's true, you'd have to adapt your scripts to not do that if you just want them to be a single item with a persistent value
