### ISSUE TITLE
[BUG] qb-jewelery inventory bug

### ISSUE THREAD

**Issue by GhostDogDK** [qbcore-framework/qb-inventory#479]
### Summary

qb-jewelery inventory bug

### Reproduction

Hi

When i smash the glas i get this almost everytime:

![Skærmbillede 2023-12-18 120959](https://github.com/qbcore-framework/qb-inventory/assets/101478737/c41a5dad-cd06-48b3-b96c-bc12245f75ef)

I can get the diamont ring and the rolex watch as it is in the config, but i newer get the goldchain. (i have try whit total empty inventory and increased the inventory size, fix nothing)
i think if it is the goldchain that makes the error 

but it looks like its right in the config and the item list. 
![Skærmbillede 2023-12-18 124](https://github.com/qbcore-framework/qb-inventory/assets/101478737/a8b9136a-8241-4781-b1f7-cb862803a68c)
![Skærmbillede 2023-12-18 1204](https://github.com/qbcore-framework/qb-inventory/assets/101478737/7024b9fe-1ffc-446b-8e8d-5c0d486740e6)

can somebody help me?

ressourcer:
![Skærmbillede 2023-12-18 125022](https://github.com/qbcore-framework/qb-inventory/assets/101478737/353599fb-9fc6-4cb3-81c0-4596384ddee9)
![Skærmbillede 2023-12-18 125125](https://github.com/qbcore-framework/qb-inventory/assets/101478737/7230ef63-1361-47dd-80ad-8ca1717bec64)
![Skærmbillede 2023-12-18 125210](https://github.com/qbcore-framework/qb-inventory/assets/101478737/6b1ce5a6-a431-4bdd-96f2-6b3f147dcb2b)

### Expected behavior

giving my items, maby the goldchain 

### Actual behavior

give me as the Picture "you have to much in yout pocket" and "item does not exist" 

### Last Updated

last week

### Custom Resources

check picture

### Resource Rename

check piture

**Comment by SQUIDzillaNFT** [comment]
i have the same problems

**Comment by Marky2701** [comment]
Me too

**Comment by Chiefink5** [comment]
yeah in the `server/main.lua` theres code to call for the "tenkgoldchain' *(recently changed from 10kgoldchain)* to be awarded if the "other chance" is odd... but doing this makes the only possible reward the "tenkgoldchain"... ive tried changing the code with over 15 different ways, *(trying to call the VitrineRewards from `(Config.VitrineRewards[item]['amount']['min'], Config.VitrineRewards[item]['amount']['max'])` and numerour other ways)* and everything else either breaks the resource or rewards absolutely nothing... 

i see others have issues with this with no response in about a month, so is there any help that we can get on this? kinda annoying that we can only get one reward from the 3 that come default, or the numerous custom items we added ourselves.
