### ISSUE TITLE
qb-inventory script error

### ISSUE THREAD

**Issue by TheRealBATIM** [qbcore-framework/qb-inventory#484]
### Summary

qb-inventory

### Reproduction

qb-inventory/server/main.lua:2400 no such export generaternadomlab in resource qb-methlab

### Expected behavior

well, I downloaded the latest version of QBcore, and when I was setting up the server, I wanted to see how qb-drugs worked, but when I try to spawn the lab key, I just get a script error out of no where.

### Actual behavior

i tryed to spawn a labkey to qb-drugs.

### Additional context

https://gyazo.com/9327bb8f743e842018432fd083f4dae1

### Last Updated

december 1 2023

### Custom Resources

No

### Resource Rename

No

**Comment by Gangstaaaaa** [comment]
meth lab is no longer a thing but you can create the export you're self just look up generaterandomlab in qb-methlab that i know of at least not a file named qb-methlab.
