### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TruJester** [qbcore-framework/qb-inventory#498]
### Summary

stash items wont save and infinitely in slot one

### Reproduction

when putting items into my stash or any stash on the account it only saves whatever is in slot one and when you pull it out it will add it to your inventory but keep it in the slot in the stash.

### Expected behavior

itmes shouls save in the stash when added and remove when taken out

### Actual behavior

items only save in the first slot and never remove

### Additional context

i have reinstalled qb inventory and redone the sql multiple times.

### Last Updated

just now

### Custom Resources

no

### Resource Rename

no

**Comment by Zorah46** [comment]
still waiting
