### ISSUE TITLE
[SUGGESTION] export for returning inventory table clientside (in inventory)

### ISSUE THREAD

**Issue by MrNewb** [qbcore-framework/qb-inventory#503]
### The problem

HasItem only returns a boolean, I would like to be able to return metadata/info from items in the inventory on the client.

### Ideal solution

an export to return the entire table of items in players inventory.

(im aware I can do this in the framework but inventory should be separate)

### Alternative solutions

I could deal and just check the framework but my bridge will be sad.

### Additional context

Thanks for coming to my ted talk

**Comment by Cocodrulo** [comment]
Added PR to add this
