### ISSUE TITLE
[BUG] Item duplication in trunks & gloveboxes

### ISSUE THREAD

**Issue by Borreke0** [qbcore-framework/qb-inventory#507]
### Summary

Item duplicate with trunk & gloveboxes

### Reproduction

1. Put item in trunk/glovebox
2. Close inventory
3. Open trunk/glovebox and swap the item back (keep inventory open so do not close)
4. Restart the server or even F8 Quit
5. Open your inventory and trunk/glovebox -> item duplicated

### Expected behavior

Items needs to get deleted from the place it swapped from

### Actual behavior

Seems that the item does not get deleted from the trunk/glovebox when not closing the inventory and the server has a restart or a user quits while having the inventory open.

### Additional context

We tested all other interactions with the inventory and it only seems to happen with the glovebox and trunk (doing some tests still to see where and why this happens.

### Last Updated

latest commit

### Custom Resources

A lot but nothing to do with inventory stuff

### Resource Rename

qb-inventory

**Comment by GhzGarage** [comment]
Add this to your server side code of the inventory until a solution is found

```
AddEventHandler('playerDropped', function(reason)
    local invStatus = Player(source).state.inv_open
    if invStatus then
        MySQL.insert('INSERT INTO bans (name, license, discord, ip, reason, expire, bannedby) VALUES (?, ?, ?, ?, ?, ?, ?)', {
            GetPlayerName(source),
            GetPlayerIdentifierByType(source, 'license'),
            GetPlayerIdentifierByType(source, 'discord'),
            GetPlayerIdentifierByType(source, 'ip'),
            'Attempting to dupe',
            2147483647,
            'qb-inventory'
        })
    end
end)
```

**Comment by GhzGarage** [comment]
@Borreke0 this should solve the issue completely

```
AddEventHandler('playerDropped', function()
	local src = source
	local inventories = { Stashes, Trunks, Gloveboxes, Drops }
	for _, inventory in pairs(inventories) do
		for _, inv in pairs(inventory) do
			if inv.isOpen == src then
				inv.isOpen = false
			end
		end
	end
end)
```

**Comment by Borreke0** [comment]
> @Borreke0 this should solve the issue completely
> 
> ```
> AddEventHandler('playerDropped', function()
> 	local src = source
> 	local inventories = { Stashes, Trunks, Gloveboxes, Drops }
> 	for _, inventory in pairs(inventories) do
> 		for _, inv in pairs(inventory) do
> 			if inv.isOpen == src then
> 				inv.isOpen = false
> 			end
> 		end
> 	end
> end)
> ```

Alright thanks! I'm going to try it and double check all the things

**Comment by Borreke0** [comment]
Still duplicates unfortunately

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-inventory/commit/2acfdec69d1fef8b7e9f9556aa662c74d7eb63cd

**Comment by jph801** [comment]
is there a fix for this, I am having the same issue.

**Comment by Darkkthought** [comment]
Have read above. 
Where would the "fix" be implemented.

**Comment by FoxeyBox** [comment]
Did you manage to fix this cause I have the same with ps inventory

**Comment by Darkkthought** [comment]
Never did get this issue figured out.
But that was months ago. I had a issue and had to relaunch my entire
server, with the June build of QB which just kicked off hundreds of other
issues with my scripts.
