### ISSUE TITLE
[BUG]stash

### ISSUE THREAD

**Issue by YouNgWINZy** [qbcore-framework/qb-inventory#508]
### Summary

After storing the item, if you close the hiding place and open it again, the item will disappear.

### Reproduction

Delete the database and re-import it

### Expected behavior

1.Player cannot save items

### Actual behavior

After storing the item, if you close the hiding place and open it again, the item will disappear.

### Last Updated

two weeks ago

### Custom Resources

qb-inventory

### Resource Rename

yes

**Comment by GhzGarage** [comment]
Sounds like a database issue

**Comment by YouNgWINZy** [comment]
How should I solve it? I have not modified the database.
