### ISSUE TITLE
[SUGGESTION] Export to get amount of slots used in Stash / Inventory

### ISSUE THREAD

**Issue by jamazzz** [qbcore-framework/qb-inventory#509]
### The problem

I would like to know the amount of slots that are already being used so I can make every x amount of slots it add a new prop inside of a truck and right now there isn't an export for that at least in the documentation.

### Ideal solution

Create the export

### Additional context

Ox inventory already has it I'm just making compatibility with qb-inventory

**Comment by GhzGarage** [comment]
I messaged you in the qb discord

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-inventory/commit/4c303fbdd8650f345615f58fade23b1e81784b84
