### ISSUE TITLE
Some Items Arent Stacking

### ISSUE THREAD

**Issue by Tkiljoy** [qbcore-framework/qb-inventory#51]
In The Inventory sometimes items wont stack even though they have stacked before also i cannot get help from the QBCore Discord for some reason it doesnt say im banned but i just cant enter it Tkiljoy#7435

**Comment by GhzGarage** [comment]
The only items that can stack are the ones that are not unique in the shared

If you cannot join the discord then you are blacklisted by the bot. Join this https://discord.gg/jeFeDRasfs
