### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by echoplire** [qbcore-framework/qb-inventory#511]
### Summary

player not responsive

### Reproduction

1. install inventory v1 log in [fly in] on my server 2. open inventory 3. close inventory 4. player stuck can't pause game, can't move, can't punch, can't move head [camera]

### Expected behavior

work

### Actual behavior

while opened player inventory then closed player inventory the player was stuck in place i can't pause the game, can't move, can't punch, can't move head [camera]

### Last Updated

today

### Custom Resources

no

### Resource Rename

no i haven't

**Comment by GhzGarage** [comment]
We don't support v1
