### ISSUE TITLE
[BUG] Item Duplication

### ISSUE THREAD

**Issue by JDot-Cv** [qbcore-framework/qb-inventory#512]
### Summary

Item duplicate with trunk & gloveboxes

### Reproduction

1) Put the item into the trunk/glovebox from inventory
2) Store vehicle
3) remove vehicle and remove from trunk but leave inventory open
4) disconnect or restart server

### Expected behavior

Remove item from trunk to inventory or delete duplicate

### Actual behavior

Duplicates Item

### Last Updated

Today (v2.0.0)

### Custom Resources

Multiple but nothing that interferes with inventory
loaf garage for vehicles

### Resource Rename

N/A

**Comment by GhzGarage** [comment]
I tried this by following your steps. I could not duplicate the item when quitting the game with the inventory open. I was able to replicate it with shutting the server off via txadmin so I added a handler for it here https://github.com/qbcore-framework/qb-inventory/commit/1430e8ddc0dfe4c23e20b0d29b61e543788388be
