### ISSUE TITLE
[BUG] Inventory Dupe

### ISSUE THREAD

**Issue by itzSparkeFam** [qbcore-framework/qb-inventory#523]
### Summary

You're able to dupe items by rightclick dropping then using while on ground and the item goes back to your inventory

### Reproduction

You're able to dupe items by rightclick dropping then using while on ground and the item goes back to your inventory

I'll provide a clip as well of doing it it with the link
https://vimeo.com/950952236?share=copy < -- Skip to about 2:55 as the start 

### Expected behavior

to just drop the item.

### Actual behavior

duplicated the item

### Additional context

https://vimeo.com/950952236?share=copy

### Last Updated

today

### Custom Resources

qb-inventory

### Resource Rename

N/A

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-inventory/commit/ff25d89862c1119c1f4fb3c650b7165f9675d9db
