### ISSUE TITLE
[SUGGESTION] Default Amount to 1

### ISSUE THREAD

**Issue by uniqueorcaname** [qbcore-framework/qb-inventory#528]
### The problem

It's a little frustrating that dragging items from shops drags the full stock if you do not set amount - defaulting the shop UI to pull 1 item at a time would be great.

### Ideal solution

When opening the shop, make amount in inventory interface default to 1

### Alternative solutions

Config to toggle whether the inventory uses 1 as default amount or all.

**Comment by GhzGarage** [comment]
That's why i made the right-click function

**Comment by mhyssasilva** [comment]
Found it guys : 

qb-inventory\html\app.js

  // Dragging and dropping
                currentlyDraggingItem: null,
                currentlyDraggingSlot: null,
                dragStartX: 0,
                dragStartY: 0,
                ghostElement: null,
                dragStartInventoryType: "player",
                transferAmount: 1,    <-------------------- JUST HERE
