### ISSUE TITLE
[BUG] Licenses Meta-Data Not Saving

### ISSUE THREAD

**Issue by krash1989** [qbcore-framework/qb-inventory#534]
### Summary

If you buy a weapon/drivers license or ID from city hall it shows information in the new inventory until you give it to another user, then it immediately goes blank in information, losing the metadata?

### Reproduction

1. Buy a weapons license at the updated qb-city hall
2. Inspect weapons license, note it has your information
3. Give weapons license to another user, note it loses all information immediately. 
4. Repeat steps for drivers license & ID. Makes it impossible for people to know if it's just some random ID you have. 

### Expected behavior

Previously the qb-inventory would save the metadata of the licenses and be able to "use" the items to flash a notification in the screen, it no longer does either.

### Actual behavior

Licenses lose meta data, even when given back to the original player they end up with just the description of the license. 

### Last Updated

Today

### Custom Resources

No

### Resource Rename

no

**Comment by Destructor** [comment]
I tested same problem, the metadata is not linked to the item or a variable deletes the information, the licenses are blank after transfer to another player or a drop on the ground, or storage (stash, trunk,..)

**Comment by rxnm** [comment]
^^got this problem too.

**Comment by Sanriku-Gaming** [comment]
https://github.com/qbcore-framework/qb-inventory/pull/547
