### ISSUE TITLE
[BUG] AddItem to trunk

### ISSUE THREAD

**Issue by TaPumpa** [qbcore-framework/qb-inventory#538]
### Summary

AddItem to trunk have been removed

### Reproduction

Hey,
it seems like you guys removed AddItems to trunk, would it be possible to bring it back?
Until you open up the trunk-inventory, you are unable to use 'exports['qb-inventory']:AddItem'

### Expected behavior

To still have this option

### Actual behavior

You have removed it, within the scripts but 'newsjob' still has it

### Last Updated

last week

### Custom Resources

my own

### Resource Rename

qb-inventory

**Comment by Storm-Trouper-NWO** [comment]
Is this getting looked in to ?

**Comment by DrMeepso** [comment]
I added this functionality in a pull request. ( https://github.com/qbcore-framework/qb-inventory/pull/539 ) as of now, it just needs to be reviewed before it can be merged!
