### ISSUE TITLE
[BUG] - METADATA PROBLEM

### ISSUE THREAD

**Issue by JoaoPedro92** [qbcore-framework/qb-inventory#542]
### Summary

There is metadata problem, that is affecting many many many scripts, even non default from qbcore

### Reproduction

1. Just pick a metadata item like id card
2. Give the item to other player
3. You will see the metadata dissapear ( on id card example it will change informations to current player witch is wrong since metadata should carry with the item not with the player )

### Expected behavior

Metadata should carry with the item not with the player, like before

### Actual behavior

Metadata is being carried by player not by item, that means depending of player metadata of item will change to simply be replaced.

### Last Updated

yesterdat

### Custom Resources

many resources that depends on metadata items

### Resource Rename

Nop

**Comment by Sanriku-Gaming** [comment]
https://github.com/qbcore-framework/qb-inventory/pull/547
