### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by smilevld** [qbcore-framework/qb-inventory#552]
### Summary

When i'm pressing the keyboard TAB and im not next to a car its shows me I open the trunk.. 

### Reproduction

I just press TAB key and Im not next to a car.. and shows me I open a trunk.
![image](https://github.com/user-attachments/assets/fef06bed-4f9f-47cf-adff-dc11f227287d)

### Expected behavior

To open only the inventory and if im next to the car on the back of the car .. then to open the trunk

### Actual behavior

I just press TAB key and Im not next to a car.. and shows me I open a trunk.

### Last Updated

today

### Custom Resources

qb-inventory

### Resource Rename

no

**Comment by Qwerty1Verified** [comment]
Can't reproduce this issue, can you add more information?
