### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SleetOnKBM** [qbcore-framework/qb-inventory#558]
### Summary

QB-Inventory Wont Open When Clicking Tab And Still Wont Work After Changing The Keybind In Game And Then Clicking The Keybind Again With No Inventory Popping Up

### Reproduction

It has been doing this since I installed the server

### Expected behavior

I expected the inventory to open and pop up

### Actual behavior

Nothing happened nothing opened

### Additional context

I also tried to do /inventory but that doesnt make the inventory pop up

### Last Updated

today

### Custom Resources

No i am not using custom resources

### Resource Rename

No it is named qb-inventory

**Comment by brandon1808** [comment]
I just did a fresh install of the framework and I'm not having any issues with the the invenotry @SleetOnKBM

**Comment by brandon1808** [comment]
also no issues when I change the inventory key bind to a different key bind
