### ISSUE TITLE
[BUG] opens other's players trunk/glovebox randomly

### ISSUE THREAD

**Issue by greenghoost** [qbcore-framework/qb-inventory#559]
### Summary

distance checking is not working for trunk or glovebox

### Reproduction

open inventory

### Expected behavior

It should not open other player's trunk or glovebox, even they are not near any trunk or inside any vehicle

### Actual behavior

when 2/3 or many players are trying to open their inventory at the same time it opens other player's trunk or glovebox inventory randomly, distance checking is not working for trunk or glovebox. Then it gives a message this inventory is currently in use because of other player player got the INV open on his end.
any fix for this problem ?

### Last Updated

today

### Custom Resources

qb-inventory

### Resource Rename

no

**Comment by Sanriku-Gaming** [comment]
I would love to see a video clip of this. I just tested and had no issues opening my inventory without the trunk, unless I was close enough to a vehicle to open the trunk.

**Comment by greenghoost** [comment]
> I would love to see a video clip of this. I just tested and had no issues opening my inventory without the trunk, unless I was close enough to a vehicle to open the trunk.

this is video link- https://drive.google.com/file/d/1a99dNwlyrvVtDxvidytiSkORISnhe24P/view?usp=sharing
at the last added other player's INV screen shot

**Comment by Faplas** [comment]
I can confirm that this is still happening, i just did it with 2 players opening trunk at same time ,then they were opening eachothers trunks

**Comment by Qwerty1Verified** [comment]
So in that video, both players were spamming tab? The second player stayed far away and was getting their own inventory, until randomly the second player got the trunk?

**Comment by Qwerty1Verified** [comment]
I forked and wrote a test fix, it works for me and may address the issue if my theory is correct.
Would a few of you be able to test it out? Just download my fork and drop in the modified files, I wouldn't bother manually changing it in case you place the changes in the wrong place.

https://github.com/Qwerty1Verified/qb-core/commit/b9d91b32ef5177c9a2e0cbce0d3962550b3c9ef8

**Comment by greenghoost** [comment]
> I forked and wrote a test fix on qb-core for the client callback logic, it works for me and may address the issue if my theory is correct. Would a few of you be able to test it out? Just download my fork and drop in the modified files, I wouldn't bother manually changing it in case you place the changes in the wrong place.
> 
> [Qwerty1Verified/qb-core@b9d91b3](https://github.com/Qwerty1Verified/qb-core/commit/b9d91b32ef5177c9a2e0cbce0d3962550b3c9ef8)

I think this fixed the issue. I tested and the problem is fixed now
