### ISSUE TITLE
[BUG] Dupe + side note of trunks

### ISSUE THREAD

**Issue by ArkyWong** [qbcore-framework/qb-inventory#563]
### Summary

Current dupe method found

### Reproduction

[https://www.dropbox.com/scl/fi/ieyfxovexfllb0o08aflp/DUPE.mp4?rlkey=9hi389s1ifv89wo31yjh6atgb&st=5tl4o0oz&dl=0](url)

### Expected behavior

Swap items

### Actual behavior

Dupes stackable items

### Last Updated

Last week

### Custom Resources

No

### Resource Rename

No

**Comment by greenghoost** [comment]
this is true

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-inventory/pull/573
