### ISSUE TITLE
[BUG] Inventory freezes/stuck

### ISSUE THREAD

**Issue by Faplas** [qbcore-framework/qb-inventory#566]
### Summary

Inventory gets stuck/freezes

### Reproduction

I cant seem to be able to constantly reproduce it, but i have seen it alot of times happening where the inventory is getting stuck, but i have had much success in reproducing it with putting some things in stash and restarting inventory

### Expected behavior

that i get the items i take out of stash

### Actual behavior

the stash gets kind of broken and doesnt give me the items, when i take 1, 2 or all items out of the stash, and closes inventory the items isnt in my inventory and is back at stash again

### Additional context

When it happends the only thing is to clear inventory in the database manual and then respawn the items from new, then it can work 1 min or multiple days without doing it again

There is a more detailed explaination here https://discord.com/channels/831626422232678481/1274666521817518192

The changes i have made to the inventory is following: Player inventory size 40 > 20, HotbarSlots 5 > 8

### Last Updated

3 weeks ago when new update was out

### Custom Resources

not anything with the inventory

### Resource Rename

no

**Comment by Qwerty1Verified** [comment]
Can only reproduce during resource restart which I believe is due to the resource UI not actually being ready to display, or the management of the UI state isn't working properly.

Are you able to provide any better reproduction steps?

**Comment by Seandope** [comment]
having the same exact issue. 
cannot even find the trunk in the database
yet even when i create a column manually it says "duplicate trunk-xxx"

**Comment by CxCore-xyz** [comment]
the fix here, https://github.com/qbcore-framework/qb-inventory/issues/580
