### ISSUE TITLE
[BUG] Give Item when No one nearby

### ISSUE THREAD

**Issue by AbdeLhere** [qbcore-framework/qb-inventory#567]
### Summary

Item remove if No one nearby

### Reproduction

- try to give an item when no one nearby
  > " Click right the item  > press give > press singl or anything "
  
  then the item will be removed from you and get notify "No one nearby"

### Expected behavior

you get the notfy "No one nearby" and you still have the item

### Actual behavior

Item removed

### Last Updated

today

### Custom Resources

no default qb base for testing

### Resource Rename

no still "qb-inventory"

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-inventory/pull/573
