### ISSUE TITLE
[BUG] Item duplicate

### ISSUE THREAD

**Issue by mnkhbldd** [qbcore-framework/qb-inventory#569]
### Summary

Item duplicate

### Reproduction

1. Just using inventory to duplicate item

### Expected behavior

Need to get fixed this bug 

### Actual behavior

Put 30x rolex item in stash then have a random 1x bandage in inventory (all of item can be duplicated). Then drag 1 rolex top of 1 bandage then move it to another slot then close inventory open again. 1 bandage will become rolex then in my inventory i have 31 rolex total and no bandage.

### Additional context

Video that shows exactly how to do it and how it duplicates.

https://github.com/user-attachments/assets/6b72526b-c792-4ff8-b52b-f25e68367c7d

### Last Updated

Lastest version of raw qb-inventory

### Custom Resources

No

### Resource Rename

qb-inventory

**Comment by HideMyFace** [comment]
Hi, tested here too, for the item down to 1 and I lost the rest.

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-inventory/pull/573
