### ISSUE TITLE
[BUG] STASH BUG MAJOR

### ISSUE THREAD

**Issue by CxCore-xyz** [qbcore-framework/qb-inventory#580]
### Summary

When you put alot of stuff in stashes then after restart you can't take out any stuff of the stash, theres no errors in F8 or txadmin console!

### Reproduction

Just putted some stuff to stash

### Expected behavior

Put the stuff in the stash take it out after restart

### Actual behavior

Put the stuff in the stash after restart you can't take it out

### Additional context

https://github.com/user-attachments/assets/52b67345-c754-4f52-8754-5b191509c1c2

### Last Updated

last day

### Custom Resources

no

### Resource Rename

no

**Comment by Crimmo44** [comment]
Also having the exact same issue.

**Comment by CxCore-xyz** [comment]
local function convert_to_json_array(input)
    -- Find the maximum slot number
    local max_slot = 0
    for _, item in pairs(input) do
        if item.slot and item.slot > max_slot then
            max_slot = item.slot
        end
    end
    -- Create the output array with null values for missing slots
    local output = {}
    for i = 1, max_slot do
        output[i] = input[i] or nil
    end
    -- Insert the items into their respective slots
    for _, item in pairs(input) do
        if item.slot then
            output[item.slot] = item
        end
    end
    return output
end

local function transform_input(input)
   local transformed = {}
   for _, item in pairs(input) do
       local slot = item.slot
       if slot then
           transformed[slot] = item
       end
   end
   return transformed
end

local function getItem(inventoryId, src, slot)
    local item
    if inventoryId == 'player' then
        local Player = QBCore.Functions.GetPlayer(src)
        item = Player.PlayerData.items[slot]
    elseif inventoryId:find('otherplayer-') then
        local targetId = tonumber(inventoryId:match('otherplayer%-(.+)'))
        local targetPlayer = QBCore.Functions.GetPlayer(targetId)
        if targetPlayer then
            item = targetPlayer.PlayerData.items[slot]
        end
    elseif inventoryId:find('drop-') then
        item = Drops[inventoryId]['items'][slot]
    else
        Inventories[inventoryId]['items']  = transform_input(Inventories[inventoryId]['items'])
        Inventories[inventoryId]['items'] = convert_to_json_array(Inventories[inventoryId]['items'])
        item = Inventories[inventoryId]['items'][slot]
    end
    return item
end

local function getIdentifier(inventoryId, src)
    if inventoryId == 'player' then
        return src
    elseif inventoryId:find('otherplayer-') then
        return tonumber(inventoryId:match('otherplayer%-(.+)'))
    else
        return inventoryId
    end
end

@Crimmo44  This code will fix the bug!

**Comment by Zack3267** [comment]
Is this code replacement or added in somewhere?

**Comment by Crimmo44** [comment]
Morning @CxCore-xyz,
Can you give us some more information?
Where do we add this?

**Comment by CxCore-xyz** [comment]
> Morning @CxCore-xyz, Can you give us some more information? Where do we add this?

I lietrally put the directories where you should add and replace above the codes.

**Comment by Zack3267** [comment]
I apologize. Its a little hard to understand where to place the things you have listed. 
Are we looking for those lines to replace them or is all of it added to the existing code?

**Comment by CxCore-xyz** [comment]
> I apologize. Its a little hard to understand where to place the things you have listed. Are we looking for those lines to replace them or is all of it added to the existing code?

this function already exists you need to change it

local inventoryItem = inventory[slot]
if not inventoryItem then
    inventoryItem = inventory[tostring(slot)]
end

if not inventoryItem or inventoryItem.name:lower() ~= item:lower() then
    print('RemoveItem: Item not found in slot')
    return false
end

-----------------------------------------
local inventoryItem = inventory --Just look for this and change the whole function with the top one


this exists too

local function getItem(inventoryId, src, slot)
local item
if inventoryId == 'player' then
local Player = QBCore.Functions.GetPlayer(src)
item = Player.PlayerData.items[slot]
elseif inventoryId:find('otherplayer-') then
local targetId = tonumber(inventoryId:match('otherplayer%-(.+)'))
local targetPlayer = QBCore.Functions.GetPlayer(targetId)
if targetPlayer then
item = targetPlayer.PlayerData.items[slot]
end
elseif inventoryId:find('drop-') then
item = Drops[inventoryId]['items'][slot]
else
Inventories[inventoryId]['items'] = transform_input(Inventories[inventoryId]['items'])
Inventories[inventoryId]['items'] = convert_to_json_array(Inventories[inventoryId]['items'])
item = Inventories[inventoryId]['items'][slot]
end
return item
end

local function getIdentifier(inventoryId, src)
if inventoryId == 'player' then
return src
elseif inventoryId:find('otherplayer-') then
return tonumber(inventoryId:match('otherplayer%-(.+)'))
else
return inventoryId
end
end

------------------------------------------
just search for the getitem and getidentifier and change them and also add theese too above the getitem

local function convert_to_json_array(input)
-- Find the maximum slot number
local max_slot = 0
for _, item in pairs(input) do
if item.slot and item.slot > max_slot then
max_slot = item.slot
end
end
-- Create the output array with null values for missing slots
local output = {}
for i = 1, max_slot do
output[i] = input[i] or nil
end
-- Insert the items into their respective slots
for _, item in pairs(input) do
if item.slot then
output[item.slot] = item
end
end
return output
end

local function transform_input(input)
local transformed = {}
for _, item in pairs(input) do
local slot = item.slot
if slot then
transformed[slot] = item
end
end
return transformed
end

**Comment by Zack3267** [comment]
Thank you so much

**Comment by CxCore-xyz** [comment]
> Thank you so much

No problem theese qbcore developers lately is lazy to fix stuff on the v2 qbcore i don't even understand why they changed the inventory when the last inventory was the best one they realeased.

**Comment by Zack3267** [comment]
So true

**Comment by BlazinFourLife** [comment]
Sorry guys had some personal life things happen, I do wish to help you guys as much as I can. As it seems you guys don’t know where to put the function I will post my entire file with the edits already made you’ll just copy everything and paste it.

**Comment by dahtslash** [comment]
Dude, you rock... So much. I've been trying to fix this for a while.  

If anyone needs the code blocks that CxCore did, here is the way I tossed it in mine and it fixed my trunks. 
qb-inventory/server/functions.lua on or around like 724
`---fix provided by https://github.com/qbcore-framework/qb-inventory/issues/580
        local inventoryItem = inventory[slot]
        if not inventoryItem then
        inventoryItem = inventory[tostring(slot)]
        end
--[[ maybe fix for stash issues
    local inventoryItem = inventory[slot]
    if not inventoryItem or inventoryItem.name:lower() ~= item:lower() then
        print('RemoveItem: Item not found in slot')
        return false
    end
]]--`  and the other piece:  
qb-inventory/server/main.lua on or around line 440
`---fix from https://github.com/qbcore-framework/qb-inventory/issues/580
-- Item move logic

local function convert_to_json_array(input)

-- Find the maximum slot number
local max_slot = 0
for _, item in pairs(input) do
if item.slot and item.slot > max_slot then
max_slot = item.slot
end
end

-- Create the output array with null values for missing slots
local output = {}
for i = 1, max_slot do
output[i] = input[i] or nil
end

-- Insert the items into their respective slots
for _, item in pairs(input) do
if item.slot then
output[item.slot] = item
end
end
return output
end

local function transform_input(input)
local transformed = {}
for _, item in pairs(input) do
local slot = item.slot
if slot then
transformed[slot] = item
end
end
return transformed
end

local function getItem(inventoryId, src, slot)
local item
if inventoryId == 'player' then
local Player = QBCore.Functions.GetPlayer(src)
item = Player.PlayerData.items[slot]
elseif inventoryId:find('otherplayer-') then
local targetId = tonumber(inventoryId:match('otherplayer%-(.+)'))
local targetPlayer = QBCore.Functions.GetPlayer(targetId)
if targetPlayer then
item = targetPlayer.PlayerData.items[slot]
end
elseif inventoryId:find('drop-') then
item = Drops[inventoryId]['items'][slot]
else
Inventories[inventoryId]['items'] = transform_input(Inventories[inventoryId]['items'])
Inventories[inventoryId]['items'] = convert_to_json_array(Inventories[inventoryId]['items'])
item = Inventories[inventoryId]['items'][slot]
end
return item
end

local function getIdentifier(inventoryId, src)
if inventoryId == 'player' then
return src
elseif inventoryId:find('otherplayer-') then
return tonumber(inventoryId:match('otherplayer%-(.+)'))
else
return inventoryId
end
end


--[[ trying to fix stashes
local function getItem(inventoryId, src, slot)
    local item
    if inventoryId == 'player' then
        local Player = QBCore.Functions.GetPlayer(src)
        item = Player.PlayerData.items[slot]
    elseif inventoryId:find('otherplayer-') then
        local targetId = tonumber(inventoryId:match('otherplayer%-(.+)'))
        local targetPlayer = QBCore.Functions.GetPlayer(targetId)
        if targetPlayer then
            item = targetPlayer.PlayerData.items[slot]
        end
    elseif inventoryId:find('drop-') == 1 then
        item = Drops[inventoryId]['items'][slot]
    else
        item = Inventories[inventoryId]['items'][slot]
    end
    return item
end

local function getIdentifier(inventoryId, src)
    if inventoryId == 'player' then
        return src
    elseif inventoryId:find('otherplayer-') then
        return tonumber(inventoryId:match('otherplayer%-(.+)'))
    else
        return inventoryId
    end
end
]]--`

This shows the code put in above the code that was shipped with the latest qb pull.  I hope this helps someone else.  Thank you again @CxCore-xyz

**Comment by Zack3267** [comment]
I still cannot get this to work. Same issues. Inventories with a lot of weight in them will not give items to players.

**Comment by Zack3267** [comment]
Thank you for trying. That still is not letting us pull inventory out of stashes its very strange

**Comment by GHOSTLYxKNIGHT** [comment]
I have implemented all fixes given, no errors but sadly still not functioning

**Comment by GhzGarage** [comment]
Working on this, been busy
