### ISSUE TITLE
Huge Issue Duplicate Item

### ISSUE THREAD

**Issue by taipham164** [qbcore-framework/qb-inventory#61]
It happen when you move all your items to stash/trunk (nothing left in personal inventory) then log out. when you log in everything in your inventory still in your personal inventory also in stash/trunk

**Comment by BlackZon77** [comment]
that happens because the stash/trunk/glove box only saves when the inventory is closed, not when an item is moved

**Comment by taipham164** [comment]
I did closed the inventory and logout. Still have that bug

**Comment by taipham164** [comment]
https://youtu.be/YsNqnzkuIpk
This is how to bug ! just get all the item out then log out !

**Comment by taipham164** [comment]
Just fixed the bug! qb-core did not save inventory when you log-out right after you move the items ! so add a line after setinventory event :
QBCore.Player.SaveInventory(src)

**Comment by nghiamas** [comment]
me too, my server have this bug too

**Comment by pushkart2** [comment]
https://github.com/qbcore-framework/qb-inventory/blob/a08738823903f74e05021210c745e804dd1a0440/server/main.lua#L972

this creates several stashes.. and not updates the existing stashes. Will fix the issue..

**Comment by Terry-Ligma** [comment]
@taipham164 When was the last time you updated your qb-inventory?

**Comment by GhzGarage** [comment]
This should fix it. https://github.com/qbcore-framework/qb-core/commit/784527b1642802792e9245a7f052599624faf220
