### ISSUE TITLE
Inventory Bug Items Duplicates after the first try

### ISSUE THREAD

**Issue by Richfie21** [qbcore-framework/qb-inventory#69]
There's a bug in qb-inventory when you store items, the rows in database duplicates , that means the first saved item  will keep coming back everytime you store or take new item, so player could lose their items and also they can spam/duplicate their item from stash to drag into players inventory

![dsc](https://user-images.githubusercontent.com/19210441/129713799-831abe63-eefa-4505-bc82-d4b0364165e2.png)

**Comment by GhzGarage** [comment]
You have the wrong sql
