### ISSUE TITLE
[Bug] A Dupe Bug

### ISSUE THREAD

**Issue by Elior2739** [qbcore-framework/qb-inventory#89]
Hi, I found a dupe bug that really easy to use

when you combine something and one of the items in a trunk, glovebox, other player inventory, stash
the item in the other inventory isn't removing but the inventory tries to remove the item from you

**Comment by GhzGarage** [comment]
Need a clip or something

**Comment by Elior2739** [comment]
https://cdn.discordapp.com/attachments/812810579923959818/881916390649516122/2021-08-30_17-47-21.mp4

**Comment by TassieRPCx** [comment]
Duping issue exists here since the item does not exist in players inventory so in which event you would just add a if statement fix.
https://github.com/qbcore-framework/qb-inventory/blob/main/server/main.lua#L22-L30

See PR https://github.com/qbcore-framework/qb-inventory/pull/91 for fix

**Comment by MrHeng1111** [comment]
Hello guy who know about this issue https://streamable.com/97d704
