### ISSUE TITLE
Missing Inventory Images

### ISSUE THREAD

**Issue by phumberdroz** [qbcore-framework/qb-inventory#99]
catfish.png
largemouthbass.png
weapon_c4.png
goldfish.png
redfish.png
grapejuice.png
tigersharkmeat.png
weapon_proximitymine.png
bluefish.png
weapon_garbagebag.png
salmon.png
weapon_remotesniper.png
killerwhalemeat.png
grape.png
stingraymeat.png
stripedbass.png
weapon_handcuffs.png

I am just wondering if we should exchange them with placeholders or if someone has them? I would open a PR.

**Comment by Demo4889** [comment]
You can always just get your own images and use them instead of waiting on others to supply images

**Comment by phumberdroz** [comment]
@Demo4889 I am not waiting on anyone. :) I am merely stating the fact that they are missing. :)
